### ISSUE TITLE
Замечания по lw2

### ISSUE THREAD

**Issue by ivklgn** [OhMyTlswp/lab2#1]
```html
      <p>Получать смс:<input class="check" type="checkbox"></p>
```

для оформления checkbox и названия лучше использовать label

**Comment by ivklgn** [comment]
```css
form {
}
```
пустой можно удалить

**Comment by ivklgn** [comment]
**task3**

```css
textarea {
  width: 70%;
  resize: none;
  height: 5vmax;
  border-color: rgb(178, 197, 209);
  border-width: 0.08vmax;
  border-style: solid;
  outline: none;
  background-color: aliceblue;
  border-radius: 7px;
}
```

при стилизации используйте классы вместо элементов
